//每日日文分享的初始清單(U05)。
//
//這一份進版控，只當作「首次啟動時的種子」：
//`src/core/japanese.js` 發現 data/japanese/entries.json 不存在時，用它建檔，
//之後的增刪改一律在 data/ 那一份上做，不會回頭改這個檔
//(同 src/core/selfRoles.js 對 config.roles 的用法)。
//
//欄位：
//  id          j_ + 四位數，建檔後不要再改(已發送紀錄是靠 id 對應的)
//  type        'idiom' 慣用句・ことわざ / 'word' 単語 / 'grammar' 文法
//  expression  表現本體
//  reading     讀音(平假名)
//  meaning     中文意思
//  level       JLPT 概略等級，僅供標示
//  tags        分類標籤
//  examples    例句，[{ja, zh}]，可以多筆
//  note        用法或文法補充，可留空字串

export const japaneseSeed = [
    ///////////////////////// 慣用句(身體部位) /////////////////////////
    {
        id: 'j_0001',
        type: 'idiom',
        expression: '猫の手も借りたい',
        reading: 'ねこのてもかりたい',
        meaning: '忙得不可開交，連貓的手都想借來用',
        level: 'N2',
        tags: ['慣用句', '動物'],
        examples: [
            {ja: '年末は猫の手も借りたいほど忙しい。', zh: '年底忙到連貓的手都想借來用。'},
        ],
        note: '常接「～ほど忙しい」一起用。',
    },
    {
        id: 'j_0002',
        type: 'idiom',
        expression: '顔が広い',
        reading: 'かおがひろい',
        meaning: '交遊廣闊、人脈很廣',
        level: 'N3',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: '彼は業界で顔が広いから、聞いてみよう。', zh: '他在這一行人面很廣，問問看他吧。'},
        ],
        note: '',
    },
    {
        id: 'j_0003',
        type: 'idiom',
        expression: '口が軽い',
        reading: 'くちがかるい',
        meaning: '嘴巴不牢、藏不住話',
        level: 'N3',
        tags: ['慣用句', '個性'],
        examples: [
            {ja: 'あの人は口が軽いから、秘密は話さないほうがいい。', zh: '那個人嘴巴不牢，最好別跟他講秘密。'},
        ],
        note: '相反是「口が堅い」。',
    },
    {
        id: 'j_0004',
        type: 'idiom',
        expression: '口が堅い',
        reading: 'くちがかたい',
        meaning: '嘴巴很牢、守得住秘密',
        level: 'N3',
        tags: ['慣用句', '個性'],
        examples: [
            {ja: '彼女は口が堅いので安心して相談できる。', zh: '她嘴很牢，可以放心找她商量。'},
        ],
        note: '',
    },
    {
        id: 'j_0005',
        type: 'idiom',
        expression: '耳が痛い',
        reading: 'みみがいたい',
        meaning: '（別人說中缺點）聽了刺耳、無地自容',
        level: 'N2',
        tags: ['慣用句', '感情'],
        examples: [
            {ja: '先輩の忠告は耳が痛いが、その通りだ。', zh: '前輩的忠告聽了刺耳，但確實沒錯。'},
        ],
        note: '不是「耳朵痛」的字面意思。',
    },
    {
        id: 'j_0006',
        type: 'idiom',
        expression: '目がない',
        reading: 'めがない',
        meaning: '非常喜歡、愛到不行',
        level: 'N2',
        tags: ['慣用句', '感情'],
        examples: [
            {ja: '母は甘い物に目がない。', zh: '我媽超愛吃甜食。'},
        ],
        note: '用「～に目がない」的形式。',
    },
    {
        id: 'j_0007',
        type: 'idiom',
        expression: '手を貸す',
        reading: 'てをかす',
        meaning: '幫忙、伸出援手',
        level: 'N3',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: 'ちょっと手を貸してくれない？', zh: '可以幫我一下嗎？'},
        ],
        note: '反過來請求協助是「手を借りる」。',
    },
    {
        id: 'j_0008',
        type: 'idiom',
        expression: '足を引っ張る',
        reading: 'あしをひっぱる',
        meaning: '扯後腿、拖累別人',
        level: 'N2',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: 'チームの足を引っ張らないように頑張る。', zh: '我會努力不拖團隊的後腿。'},
        ],
        note: '',
    },
    {
        id: 'j_0009',
        type: 'idiom',
        expression: '腰が低い',
        reading: 'こしがひくい',
        meaning: '態度謙虛、待人客氣',
        level: 'N2',
        tags: ['慣用句', '個性'],
        examples: [
            {ja: '社長なのに腰が低い人だ。', zh: '明明是社長，卻很謙和。'},
        ],
        note: '相反是「腰が高い」（傲慢），但後者現代較少用。',
    },
    {
        id: 'j_0010',
        type: 'idiom',
        expression: '骨が折れる',
        reading: 'ほねがおれる',
        meaning: '費力氣、很辛苦',
        level: 'N2',
        tags: ['慣用句', '工作'],
        examples: [
            {ja: 'この作業はなかなか骨が折れる。', zh: '這個工作相當累人。'},
        ],
        note: '字面是「骨折」，但慣用義是「吃力」。',
    },
    {
        id: 'j_0011',
        type: 'idiom',
        expression: '息を呑む',
        reading: 'いきをのむ',
        meaning: '（因驚訝或美景）屏息、倒抽一口氣',
        level: 'N2',
        tags: ['慣用句', '感情'],
        examples: [
            {ja: '息を呑むような絶景だった。', zh: '是令人屏息的絕景。'},
        ],
        note: '',
    },
    {
        id: 'j_0012',
        type: 'idiom',
        expression: '胸を張る',
        reading: 'むねをはる',
        meaning: '抬頭挺胸、充滿自信',
        level: 'N2',
        tags: ['慣用句', '感情'],
        examples: [
            {ja: '胸を張って結果を報告できる。', zh: '可以抬頭挺胸地報告成果。'},
        ],
        note: '',
    },
    {
        id: 'j_0013',
        type: 'idiom',
        expression: '首を長くする',
        reading: 'くびをながくする',
        meaning: '翹首期盼、等得望眼欲穿',
        level: 'N2',
        tags: ['慣用句', '感情'],
        examples: [
            {ja: '首を長くして返事を待っている。', zh: '正望眼欲穿地等回覆。'},
        ],
        note: '多用「首を長くして待つ」。',
    },
    {
        id: 'j_0014',
        type: 'idiom',
        expression: '鼻が高い',
        reading: 'はながたかい',
        meaning: '（因某事）感到光榮、驕傲',
        level: 'N2',
        tags: ['慣用句', '感情'],
        examples: [
            {ja: '息子が優勝して鼻が高い。', zh: '兒子拿了冠軍，我很光榮。'},
        ],
        note: '是「與有榮焉」，不是罵人自大。',
    },
    {
        id: 'j_0015',
        type: 'idiom',
        expression: '頭が固い',
        reading: 'あたまがかたい',
        meaning: '死腦筋、不知變通',
        level: 'N3',
        tags: ['慣用句', '個性'],
        examples: [
            {ja: '父は頭が固くて、新しいやり方を認めない。', zh: '我爸很死腦筋，不接受新做法。'},
        ],
        note: '相反是「頭が柔らかい」。',
    },
    {
        id: 'j_0016',
        type: 'idiom',
        expression: '気が合う',
        reading: 'きがあう',
        meaning: '合得來、投緣',
        level: 'N3',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: '彼とは初対面から気が合った。', zh: '和他第一次見面就很投緣。'},
        ],
        note: '',
    },
    {
        id: 'j_0017',
        type: 'idiom',
        expression: '気が短い',
        reading: 'きがみじかい',
        meaning: '性子急、沒耐性',
        level: 'N3',
        tags: ['慣用句', '個性'],
        examples: [
            {ja: '気が短い人は行列が苦手だ。', zh: '性子急的人受不了排隊。'},
        ],
        note: '相反是「気が長い」。',
    },
    {
        id: 'j_0018',
        type: 'idiom',
        expression: '気を使う',
        reading: 'きをつかう',
        meaning: '費心留意、顧慮他人',
        level: 'N3',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: '後輩にそんなに気を使わなくていいよ。', zh: '不用對學弟妹那麼顧慮啦。'},
        ],
        note: '「気を遣う」也是同一個詞的漢字寫法。',
    },
    {
        id: 'j_0019',
        type: 'idiom',
        expression: '手が空く',
        reading: 'てがあく',
        meaning: '（手邊的事忙完）有空了',
        level: 'N3',
        tags: ['慣用句', '工作'],
        examples: [
            {ja: '手が空いたら手伝ってください。', zh: '你有空的話請幫我一下。'},
        ],
        note: '相反是「手が離せない」（走不開）。',
    },
    {
        id: 'j_0020',
        type: 'idiom',
        expression: '肩を持つ',
        reading: 'かたをもつ',
        meaning: '偏袒、幫某一方說話',
        level: 'N2',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: 'どうしていつも彼の肩を持つの？', zh: '你為什麼老是偏袒他？'},
        ],
        note: '',
    },
    ///////////////////////// 慣用句(行為) /////////////////////////
    {
        id: 'j_0021',
        type: 'idiom',
        expression: '水に流す',
        reading: 'みずにながす',
        meaning: '既往不咎、把過去一筆勾銷',
        level: 'N2',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: '昔のことは水に流そう。', zh: '過去的事就一筆勾銷吧。'},
        ],
        note: '',
    },
    {
        id: 'j_0022',
        type: 'idiom',
        expression: '油を売る',
        reading: 'あぶらをうる',
        meaning: '偷懶閒聊、摸魚',
        level: 'N2',
        tags: ['慣用句', '工作'],
        examples: [
            {ja: 'どこで油を売っていたんだ。', zh: '你剛剛跑去哪裡摸魚了？'},
        ],
        note: '源自江戶時代賣油商邊聊天邊做生意。',
    },
    {
        id: 'j_0023',
        type: 'idiom',
        expression: '道草を食う',
        reading: 'みちくさをくう',
        meaning: '半路上耽擱、繞路貪玩',
        level: 'N2',
        tags: ['慣用句', '日常'],
        examples: [
            {ja: '道草を食わずにまっすぐ帰りなさい。', zh: '不要在路上晃，直接回家。'},
        ],
        note: '',
    },
    {
        id: 'j_0024',
        type: 'idiom',
        expression: '羽を伸ばす',
        reading: 'はねをのばす',
        meaning: '（脫離拘束後）放鬆玩個痛快',
        level: 'N2',
        tags: ['慣用句', '日常'],
        examples: [
            {ja: '試験が終わったので羽を伸ばした。', zh: '考完試了，好好放鬆了一番。'},
        ],
        note: '',
    },
    {
        id: 'j_0025',
        type: 'idiom',
        expression: '釘を刺す',
        reading: 'くぎをさす',
        meaning: '事先叮嚀、把話說在前頭',
        level: 'N1',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: '遅刻しないように釘を刺しておいた。', zh: '已經先叮嚀過他別遲到了。'},
        ],
        note: '',
    },
    {
        id: 'j_0026',
        type: 'idiom',
        expression: '匙を投げる',
        reading: 'さじをなげる',
        meaning: '放棄、認為無藥可救',
        level: 'N1',
        tags: ['慣用句', '感情'],
        examples: [
            {ja: '医者も匙を投げるほどの状態だった。', zh: '當時的狀況連醫生都束手無策。'},
        ],
        note: '源自醫生放棄調藥。',
    },
    {
        id: 'j_0027',
        type: 'idiom',
        expression: '舌を巻く',
        reading: 'したをまく',
        meaning: '嘆為觀止、佩服得說不出話',
        level: 'N1',
        tags: ['慣用句', '感情'],
        examples: [
            {ja: '彼の記憶力には舌を巻いた。', zh: '他的記憶力讓人嘆為觀止。'},
        ],
        note: '',
    },
    {
        id: 'j_0028',
        type: 'idiom',
        expression: '目を通す',
        reading: 'めをとおす',
        meaning: '大致看過、瀏覽一遍',
        level: 'N2',
        tags: ['慣用句', '工作'],
        examples: [
            {ja: '会議の前に資料に目を通しておいてください。', zh: '開會前請先把資料看過一遍。'},
        ],
        note: '',
    },
    {
        id: 'j_0029',
        type: 'idiom',
        expression: '大目に見る',
        reading: 'おおめにみる',
        meaning: '寬容看待、睜一隻眼閉一隻眼',
        level: 'N2',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: '今回は初めてだから大目に見よう。', zh: '這次是第一次，就寬容一點吧。'},
        ],
        note: '',
    },
    {
        id: 'j_0030',
        type: 'idiom',
        expression: '腹を割る',
        reading: 'はらをわる',
        meaning: '推心置腹、把心裡話講開',
        level: 'N1',
        tags: ['慣用句', '人際'],
        examples: [
            {ja: '一度腹を割って話し合おう。', zh: '找個時間把話講開吧。'},
        ],
        note: '常用「腹を割って話す」。',
    },
    ///////////////////////// ことわざ /////////////////////////
    {
        id: 'j_0031',
        type: 'idiom',
        expression: '石の上にも三年',
        reading: 'いしのうえにもさんねん',
        meaning: '有恆為成功之本；再冷的石頭坐三年也會暖',
        level: 'N2',
        tags: ['ことわざ', '努力'],
        examples: [
            {ja: '石の上にも三年、まずは続けてみよう。', zh: '滴水穿石，先撐下去再說。'},
        ],
        note: '',
    },
    {
        id: 'j_0032',
        type: 'idiom',
        expression: '猿も木から落ちる',
        reading: 'さるもきからおちる',
        meaning: '智者千慮必有一失',
        level: 'N2',
        tags: ['ことわざ', '動物'],
        examples: [
            {ja: '猿も木から落ちるというし、気にしないで。', zh: '連猴子都會從樹上掉下來，別在意。'},
        ],
        note: '同義：弘法にも筆の誤り。',
    },
    {
        id: 'j_0033',
        type: 'idiom',
        expression: '七転び八起き',
        reading: 'ななころびやおき',
        meaning: '跌倒七次爬起八次，屢敗屢戰',
        level: 'N2',
        tags: ['ことわざ', '努力'],
        examples: [
            {ja: '七転び八起きの精神でやり直す。', zh: '抱著屢敗屢戰的精神重來一次。'},
        ],
        note: '',
    },
    {
        id: 'j_0034',
        type: 'idiom',
        expression: '継続は力なり',
        reading: 'けいぞくはちからなり',
        meaning: '堅持就是力量',
        level: 'N2',
        tags: ['ことわざ', '努力'],
        examples: [
            {ja: '毎日十分でもいい。継続は力なりだ。', zh: '每天十分鐘也好，堅持就是力量。'},
        ],
        note: '「なり」是文言的斷定助動詞，等於「である」。',
    },
    {
        id: 'j_0035',
        type: 'idiom',
        expression: '急がば回れ',
        reading: 'いそがばまわれ',
        meaning: '欲速則不達，繞遠路反而快',
        level: 'N2',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '急がば回れで、基礎から復習した。', zh: '欲速則不達，我從基礎開始複習。'},
        ],
        note: '「急がば」是文言的假定形。',
    },
    {
        id: 'j_0036',
        type: 'idiom',
        expression: '覆水盆に返らず',
        reading: 'ふくすいぼんにかえらず',
        meaning: '覆水難收',
        level: 'N1',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '謝っても覆水盆に返らずだ。', zh: '就算道歉也覆水難收了。'},
        ],
        note: '出自中國典故。',
    },
    {
        id: 'j_0037',
        type: 'idiom',
        expression: '出る杭は打たれる',
        reading: 'でるくいはうたれる',
        meaning: '樹大招風、出頭的椽子先爛',
        level: 'N1',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '出る杭は打たれるが、それでも挑戦したい。', zh: '雖然樹大招風，我還是想挑戰。'},
        ],
        note: '',
    },
    {
        id: 'j_0038',
        type: 'idiom',
        expression: '花より団子',
        reading: 'はなよりだんご',
        meaning: '務實勝於風雅；比起賞花更想吃丸子',
        level: 'N2',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '花見に行っても花より団子だ。', zh: '就算去賞花，重點也還是吃的。'},
        ],
        note: '',
    },
    {
        id: 'j_0039',
        type: 'idiom',
        expression: '十人十色',
        reading: 'じゅうにんといろ',
        meaning: '每個人各有各的想法與喜好',
        level: 'N2',
        tags: ['ことわざ', '四字熟語'],
        examples: [
            {ja: '好みは十人十色だから、正解はない。', zh: '喜好因人而異，沒有標準答案。'},
        ],
        note: '注意讀「といろ」不是「じっしょく」。',
    },
    {
        id: 'j_0040',
        type: 'idiom',
        expression: '一石二鳥',
        reading: 'いっせきにちょう',
        meaning: '一石二鳥、一舉兩得',
        level: 'N2',
        tags: ['ことわざ', '四字熟語'],
        examples: [
            {ja: '通勤で歩けば運動にもなって一石二鳥だ。', zh: '通勤用走的還能運動，一舉兩得。'},
        ],
        note: '',
    },
    {
        id: 'j_0041',
        type: 'idiom',
        expression: '弘法にも筆の誤り',
        reading: 'こうぼうにもふでのあやまり',
        meaning: '再厲害的人也會出錯',
        level: 'N1',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '弘法にも筆の誤り、先生でも間違える。', zh: '再厲害的人也會出錯，老師也會犯錯。'},
        ],
        note: '弘法＝空海，書法名家。',
    },
    {
        id: 'j_0042',
        type: 'idiom',
        expression: '三日坊主',
        reading: 'みっかぼうず',
        meaning: '三分鐘熱度',
        level: 'N2',
        tags: ['ことわざ', '個性'],
        examples: [
            {ja: '日記はいつも三日坊主で終わる。', zh: '寫日記總是三分鐘熱度。'},
        ],
        note: '',
    },
    {
        id: 'j_0043',
        type: 'idiom',
        expression: '塵も積もれば山となる',
        reading: 'ちりもつもればやまとなる',
        meaning: '積少成多、聚沙成塔',
        level: 'N2',
        tags: ['ことわざ', '努力'],
        examples: [
            {ja: '毎日五個ずつ覚えれば、塵も積もれば山となる。', zh: '每天背五個，積少成多。'},
        ],
        note: '',
    },
    {
        id: 'j_0044',
        type: 'idiom',
        expression: '猫に小判',
        reading: 'ねこにこばん',
        meaning: '對牛彈琴、給不懂的人再好的東西也沒用',
        level: 'N2',
        tags: ['ことわざ', '動物'],
        examples: [
            {ja: '興味のない人に名品をあげても猫に小判だ。', zh: '送名品給沒興趣的人，等於對牛彈琴。'},
        ],
        note: '小判是江戶時代的金幣。',
    },
    {
        id: 'j_0045',
        type: 'idiom',
        expression: '馬の耳に念仏',
        reading: 'うまのみみにねんぶつ',
        meaning: '對牛彈琴（強調說了也不聽）',
        level: 'N1',
        tags: ['ことわざ', '動物'],
        examples: [
            {ja: '何度注意しても馬の耳に念仏だ。', zh: '講幾次都當耳邊風。'},
        ],
        note: '與「猫に小判」的差別：這句偏「聽不進去」，那句偏「不識貨」。',
    },
    {
        id: 'j_0046',
        type: 'idiom',
        expression: '二兎を追う者は一兎をも得ず',
        reading: 'にとをおうものはいっとをもえず',
        meaning: '同時追兩隻兔子，一隻也抓不到',
        level: 'N1',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '二兎を追う者は一兎をも得ず、まず一つに集中しよう。', zh: '貪多嚼不爛，先專心做一件事。'},
        ],
        note: '',
    },
    {
        id: 'j_0047',
        type: 'idiom',
        expression: '千里の道も一歩から',
        reading: 'せんりのみちもいっぽから',
        meaning: '千里之行始於足下',
        level: 'N2',
        tags: ['ことわざ', '努力'],
        examples: [
            {ja: '千里の道も一歩から、今日から始めよう。', zh: '千里之行始於足下，今天就開始吧。'},
        ],
        note: '',
    },
    {
        id: 'j_0048',
        type: 'idiom',
        expression: '案ずるより産むが易し',
        reading: 'あんずるよりうむがやすし',
        meaning: '事情做起來往往沒有想像中難',
        level: 'N1',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '案ずるより産むが易し、やってみたら簡単だった。', zh: '想太多不如做做看，做了才發現很簡單。'},
        ],
        note: '',
    },
    {
        id: 'j_0049',
        type: 'idiom',
        expression: '郷に入っては郷に従え',
        reading: 'ごうにいってはごうにしたがえ',
        meaning: '入境隨俗',
        level: 'N1',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '郷に入っては郷に従え、この会社のやり方に合わせよう。', zh: '入境隨俗，配合這家公司的做法吧。'},
        ],
        note: '「入って」這裡讀「いって」。',
    },
    {
        id: 'j_0050',
        type: 'idiom',
        expression: '灯台下暗し',
        reading: 'とうだいもとくらし',
        meaning: '越近的地方越看不清、當局者迷',
        level: 'N1',
        tags: ['ことわざ', '處世'],
        examples: [
            {ja: '灯台下暗しで、鍵はポケットにあった。', zh: '燈下黑，鑰匙就在口袋裡。'},
        ],
        note: '這裡的「灯台」是舊式油燈的燈架，不是燈塔。',
    },
    ///////////////////////// 文法 /////////////////////////
    {
        id: 'j_0051',
        type: 'grammar',
        expression: '～ようにする',
        reading: '～ようにする',
        meaning: '努力做到、養成習慣（意志性的持續努力）',
        level: 'N4',
        tags: ['文法'],
        examples: [
            {ja: '毎日日本語を話すようにしている。', zh: '我盡量每天都說日文。'},
        ],
        note: '與「～ことにする」的差別：這句是「持續努力」，那句是「一次做出的決定」。',
    },
    {
        id: 'j_0052',
        type: 'grammar',
        expression: '～ことにする',
        reading: '～ことにする',
        meaning: '（自己）決定要做某事',
        level: 'N4',
        tags: ['文法'],
        examples: [
            {ja: '来月から留学することにした。', zh: '我決定下個月開始去留學。'},
        ],
        note: '「～ことになる」則是「（被安排）變成這樣」，主體不同。',
    },
    {
        id: 'j_0053',
        type: 'grammar',
        expression: '～たばかり',
        reading: '～たばかり',
        meaning: '剛剛才做完某事',
        level: 'N4',
        tags: ['文法'],
        examples: [
            {ja: '日本に来たばかりで、まだ慣れていない。', zh: '我才剛來日本，還不習慣。'},
        ],
        note: '和「～たところ」的差別：「ばかり」偏說話者的主觀感受，時間可以拉長。',
    },
    {
        id: 'j_0054',
        type: 'grammar',
        expression: '～に違いない',
        reading: '～にちがいない',
        meaning: '一定是…（強烈的推測）',
        level: 'N3',
        tags: ['文法'],
        examples: [
            {ja: '電気がついている。彼はまだ会社にいるに違いない。', zh: '燈還亮著，他一定還在公司。'},
        ],
        note: '比「～はずだ」更強調說話者的確信。',
    },
    {
        id: 'j_0055',
        type: 'grammar',
        expression: '～わけではない',
        reading: '～わけではない',
        meaning: '並不是說…（部分否定）',
        level: 'N3',
        tags: ['文法'],
        examples: [
            {ja: '嫌いなわけではないが、あまり食べない。', zh: '並不是討厭，只是不太吃。'},
        ],
        note: '全面否定要用「～わけがない」（不可能）。',
    },
    {
        id: 'j_0056',
        type: 'grammar',
        expression: '～わけにはいかない',
        reading: '～わけにはいかない',
        meaning: '（基於情理或立場）不能這麼做',
        level: 'N3',
        tags: ['文法'],
        examples: [
            {ja: '約束したから、行かないわけにはいかない。', zh: '都答應人家了，不去不行。'},
        ],
        note: '不是能力上的「できない」，是道理上的「不能」。',
    },
    {
        id: 'j_0057',
        type: 'grammar',
        expression: '～てしまう',
        reading: '～てしまう',
        meaning: '不小心做了…／完全做完了',
        level: 'N4',
        tags: ['文法'],
        examples: [
            {ja: '大事な書類をなくしてしまった。', zh: '把重要的文件弄丟了。'},
        ],
        note: '口語會縮成「～ちゃう」「～じゃう」。',
    },
    {
        id: 'j_0058',
        type: 'grammar',
        expression: '～ながらも',
        reading: '～ながらも',
        meaning: '雖然…但是…（逆接）',
        level: 'N2',
        tags: ['文法'],
        examples: [
            {ja: '狭いながらも、居心地のいい部屋だ。', zh: '雖然窄，卻是很舒服的房間。'},
        ],
        note: '和表示同時進行的「～ながら」不同，這裡是逆接。',
    },
    {
        id: 'j_0059',
        type: 'grammar',
        expression: '～に関して',
        reading: '～にかんして',
        meaning: '關於…（書面語）',
        level: 'N3',
        tags: ['文法'],
        examples: [
            {ja: 'この件に関しては、後日ご連絡します。', zh: '關於這件事，日後再與您聯繫。'},
        ],
        note: '口語多用「～について」。',
    },
    {
        id: 'j_0060',
        type: 'grammar',
        expression: '～ば～ほど',
        reading: '～ば～ほど',
        meaning: '越…就越…',
        level: 'N3',
        tags: ['文法'],
        examples: [
            {ja: '練習すればするほど上手になる。', zh: '越練習就越熟練。'},
        ],
        note: 'い形容詞用「～ければ～ほど」，名詞・な形容詞用「～であればあるほど」。',
    },
]

export default japaneseSeed
